version: '3.9'
services:
  app:
    image: doelia/the-french-tototte:main
    ports:
    - "9098:80"
    environment:
      - VIRTUAL_HOST=the-french-tototte.doelia.fr
    restart: always

networks:
  default:
    name: http_public
    external: true
